### ISSUE TITLE
Recursive Git pull tries to get tradingview/charting_library

### ISSUE THREAD

**Issue by freecrm** [MimeticMarkets/sputnik#72]
Recursive GIT pull of sputnik errors:

Clone of 'https://github.com/tradingview/charting_library' into submodule path 'charting_library' failed

**Comment by sameerparekh** [comment]
In order to get access to the charting_library github you'll need to get access from the folks at Trading View:

https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

We'll have to add that to the wiki.
