### ISSUE TITLE
bitcoin 0.8.6....failed

### ISSUE THREAD

**Issue by freecrm** [MimeticMarkets/sputnik#73]
bitcoin-0.8.6 not installed. Installing... failed

First, no idea why you are installing such an old version.  Strange.

Second, compiling 0.8.6 is not an easy thing to do.....manually not so difficult but there's no way you can automate this.

**Comment by sameerparekh** [comment]
Can you provide the install.log file?

**Comment by ysobolev** [comment]
There is no good reason for having such an old version anymore. Originally, it was compiled to make sure it compiles against db4.8. Bbitcoind in Ubuntu compiled against db5 and would have memory issues.

We should upgrade to the latest. We can either add the PPA listed here https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin or compile our own. The PPA version seems to use db4.8.

**Comment by adelorenzo** [comment]
An easy way to fix this is to change the 2nd line of the file ~/sputnik/install/profiles/minimal/deps/source/02-bitcoin-0.8.6 that reads 
SOURCE=https://bitcoin.org/bin/0.8.6/bitcoin-0.8.6-linux.tar.gz
to
SOURCE=https://bitcoin.org/bin/bitcoin-core-0.8.6/bitcoin-0.8.6-linux.tar.gz
